### ISSUE TITLE
Stopped working - LMY47V

### ISSUE THREAD

**Issue by nimitsolanki** [gkraynov/nexus-4-navfix#4]
Hi @gkraynov , Thanks for the life saver patch. It was working fine with Android 5.1.1, but suddenly it stopped working. Then I tried to update it again, but no luck. I also tried to flash previous android versions and their update patch, but still not working. 

Do you have any idea, what went wrong ?
Thanks,
Nimit

**Comment by RavanH** [comment]
Strange, it looks like  this happend on my device too. Had it working fine and was happily ignoring the latest update nag (because there is no patch for LMY48I yet) until two days ago. The soft-menu started becoming unresponsive again. At first only sometimes but now completely dead... 

Tried re-applying the patch but it does not solve the issue. I fear the phone is about to become useless (again) because sometimes the complete screen becomes one big dead zone. Seeing more and more ghost taps these days too :(

**Comment by comeonfox** [comment]
I flashed the patch, but the nav bar and the status bar all gone, what happend?
