### ISSUE TITLE
LMY48T

### ISSUE THREAD

**Issue by privetpoka** [gkraynov/nexus-4-navfix#7]
Hello, Gregory.
I haven't found version for lmy48t. I wonder if u have it? 
U can also answer in russian if it's ok. 
Thank u very much!

**Comment by techkid2000** [comment]
Hi there,

I'm currently also running this build! A navfix would be very much appreciatie!!

Thanks, cheers

Mathijs

**Comment by Rahoool** [comment]
Hi,

l also need patch for my nexus 4 LMY48T build.
Please help asap ... This soft key issue is just frustrating.

Thanks

**Comment by mbuc82** [comment]
Hello,

at first thank you very much for this nice patch, it still works really good for the related builds.
As there is "just" a patch for build LMY48M available, i´m also forced to use this version (if i want to use my nav-bar-buttons). It would be really nice to have a patch for the latest build LMY48T.

Thanks a lot

Cheers, Marco

**Comment by iLikeKoffee** [comment]
Hello. 
Thank you very much for your work, It's awesome. I'm looking forward for LMY48T patch too.
Can LMY48M patch be installed on LMY48T build? Or it isn't an option?
Should  make a try to install one? If not, how can I help you with build?

Sincerely, Alexey

**Comment by mbuc82** [comment]
Hello together,

since Gregory has no change to test anymore and the releases for newer android version will take more time, i did a build for LMY48T on my own and tested it on my Nexus 4.

Since now everything works as expected, the complete navigation buttons are usable, so i forked the whole project and released the new version:

https://github.com/mbuc82/nexus-4-navfix/releases/tag/LMY48T

Please let me know, if everything works for you as well, or if you have any kind of problems.

As already mentioned on that page, the build comes with absolutely no warrantly (but hopefully it works for all of your phones ;) ).

Best regards

Marco

**Comment by iLikeKoffee** [comment]
Awesome!

**Comment by andreykadatsky** [comment]
Thanks Marco!

**Comment by iLikeKoffee** [comment]
I think that should be closed=)

**Comment by omshivaprakash** [comment]
https://github.com/mbuc82/nexus-4-navfix/releases/tag/LMY48T doesn't seem to work :(

**Comment by velasiped** [comment]
Привет Григорий!
Спасибо за отличный фикс! Все работает. Скажи а  на кастомной прошивке будет работать? cyanogenmod 12.1 например? Или можно сделать для него версию? Будем очень благодарны!)

**Comment by castilho-rs** [comment]
Marco, just used your fix for LMY48T and it worked perfectly, thanks

**Comment by leonchuk** [comment]
I have the same build number
but the application is not installed ((

![12675075_10207747650796784_1628573764_o](https://cloud.githubusercontent.com/assets/11705213/13034793/ea540456-d347-11e5-9397-26ddd8a8cc43.jpg)
![12751667_10207747643636605_645779129_o](https://cloud.githubusercontent.com/assets/11705213/13034794/ea57ae12-d347-11e5-9189-8b6a285b3adf.jpg)

**Comment by Ljzero** [comment]
Thank You so much Mr Marco, it worked like a gem. :) :100:
